### ISSUE TITLE
Dragging with mouse doesn't work when min and/or max is set

### ISSUE THREAD

**Issue by jgrumboe** [thomasloven/round-slider#10]
Hi,

I want to use this slider:
```
<round-slider
      value=40
      arcLength=180
      startAngle=180
      min=38
      max=56
      step=1
    ></round-slider>
```
It renders well, but dragging with mouse doesn't work.
When I remove min and max it works.
As soon as I use min or max it doesn't.

Can you help me?
BR,
Johannes

**Comment by jgrumboe** [comment]
Additional info:
Dragging works when I use min=0 and max=18.
Since my usecase is a climate control, I can work with this by working with an offset to the actual temperature.

It seem as higher the min value is set the more likely mouse dragging doesn't work.

**Comment by thomasloven** [comment]
Can't reproduce

https://codepen.io/thomasloven/pen/rNNogZE

**Comment by jgrumboe** [comment]
Maybe it happens here because we use it in combination with Svelte?!

**Comment by ebrensi** [comment]
> Can't reproduce
> 
> https://codepen.io/thomasloven/pen/rNNogZE

I am not able to drag the slider in this example on Chrome 80.0.3897.xxx for Android.

**Comment by jgrumboe** [comment]
Will close this one, as I don't use the component anymore and keeping it open doesn't make sense for me.
