### ISSUE TITLE
Feature Request: click on track to change value

### ISSUE THREAD

**Issue by Scrounger** [thomasloven/round-slider#12]
@thomasloven 

First, thanks you for this great library. 
I ported it to be used in [iobroker](https://www.iobroker.net/) VIS.

One feature the community and i missing is the click on track (arc) to change the value. Like you can do this on material slider like in [this example](https://material-components.github.io/material-components-web-catalog/#/component/slider).

Could you maybe implement that?

**Comment by qusenazlas** [comment]
elem.addEventListener("mousedown", e => {
        let posX = e.offsetX;
        let posY = e.offsetY;
        let width = baseRect.width / 2;
        let height = baseRect.height / 2;
        let deltaY = height - posY;
        let deltaX = width - posX;
        let deg = (Math.atan2(deltaY, deltaX) * 180) / Math.PI;
        deg = deg - 90;
        if (deg < 0 && deg >= -270) {
          deg = deg + 360;
        }
        this.value = deg;
      });

I try this code. my start angle is -90 deg try to config this code.

**Comment by thomasloven** [comment]
I'll see what I can do.

**Comment by jon-joshua** [comment]
#14 

Just put in a pull request

**Comment by thomasloven** [comment]
Added in version 0.5.0!
