### ISSUE TITLE
Feature request: Add a mode to fill the slider from an upper-end

### ISSUE THREAD

**Issue by Shulyaka** [thomasloven/round-slider#21]
Hi!

Currently, in the single slider mode, the slider is filled with blue from the lower bound (i.e. `min`) up to `value`, and with gray color between the `value` and `max`. That could represent to the user that something (e.g. a heater) is active below the setpoint. However if you want to represent an AC unit, which is active above the setpoint instead, I think it would be more natural to fill in the upper arc with the color instead of the lower arc.
The rtl does not help with this case because flipping rtl also flips the sides of `min` and `max` values which is not desired.

**Comment by thomasloven** [comment]
Can't you just change the bar and path colors?

**Comment by Shulyaka** [comment]
Yes, that could be a workaround, however:

1. It would be just more convenient to have a property
2. Wouldn't that also change the appearance of `disabled` mode?

It's up to you to decide whether the idea worth it or not, of course.

**Comment by Shulyaka** [comment]
Thank you!
