### ISSUE TITLE
Issue using round-slider in React

### ISSUE THREAD

**Issue by cdevlegend** [thomasloven/round-slider#35]
Hello. Nice to meet you.
I was trying to use your round-slider library but I am not sure how to use it in React.
Could you kindly teach me please?
I will wait for you.
Best regards.

**Comment by thomasloven** [comment]
I've never used React myself, but I understand there's always been issues with React and Web Components such as this one.

This might help?
https://react.dev/reference/react-dom/components#custom-html-elements
