### ISSUE TITLE
Doesn't work in Firefox 60.9.0esr

### ISSUE THREAD

**Issue by jacmet** [thomasloven/round-slider#7]
Trying out the example in Firefox 60.9.0esr I get:

round-slider:81:8    ReferenceError: customElements is not defined

It would be great if this could also work in Firefox

**Comment by thomasloven** [comment]
customElements is not supported by default in Firefox versions earlier than 63 (released october 2018).

I *think* you can make it work in v 60 by setting `dom.webcomponents.customelements.enabled` to `true` in `about:config`.
Or maybe a [polyfill](https://www.npmjs.com/package/@webcomponents/custom-elements) could work, but I'm no expert...

**Comment by jacmet** [comment]
So far no luck with dom.webcomponents.customelements.enabled. Pity, as v60 is the version shipped in recent distributions like Debian 10, so having E.G. HA break because of it would be unfortunate.

**Comment by thomasloven** [comment]
Is HA (assuming that means Home Assistant) actually a problem for you?
Because Home Assistant use the suggested polyfills and should work.

**Comment by jacmet** [comment]
Sorry, Debian in the man time updated to 68.3.0esr (where it works) so I can no longer test with v60
