### ISSUE TITLE
How to use in Home Assistant?

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/round-slider#8]
The round-slider-with-a-bulb is default in HA.
As the n00b I am, how do I get the round-slider (without the bulb) into HA (HACS)?

Thanks for your impressive work contributing to HA!

Cheers.

**Comment by thomasloven** [comment]
You'd have to create a custom lovelace-card - which this is not - that implements it.
https://developers.home-assistant.io/docs/en/lovelace_custom_card.html

**Comment by kongo09** [comment]
@thomasloven In the unlikely event of wondering what could be the next amazing card you could contribute to the community, such a round-slider card would be marvelous. It seems you've done the heavy lifting already.

Thanks for all the work!

**Comment by thomasloven** [comment]
This is used in the `light` and `thermostat` cards.

**Comment by kongo09** [comment]
I just took a look at your slider card. Maybe you could extend that? Controllers should be the same?

Happy to buy you a coffee...

Edit: bought you a coffee. 
https://www.buymeacoffee.com/uqD6KHCdJ
